spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
upload:
  dir: "/home/vladimir/IdeaProjects/Homework-Sky-Pro-Third-Course/src/main/resources/files/"
