spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: "db.changelog/db.changelog.yml"

upload:
  dir: "/home/vladimir/IdeaProjects/Homework-Sky-Pro-Third-Course/src/main/resources/files/"

logging:
  level:
    ru.hogwarts.school.service: trace
server:
  port: 8080
